---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - при оформленим заказа пользователь должен быть зарегистрирован и авторизован
  - при оформлении заказа у пользователя должны быть указаны контактные данные
  - нельзя положить в корзину товар, если его количество равно 0
